"""add maintenance detail fields

Revision ID: 6d4aa8f15d3f
Revises: e63ba9453321
Create Date: 2026-07-15 16:38:17.611969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d4aa8f15d3f'
down_revision: Union[str, None] = 'e63ba9453321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_logs', sa.Column('maintenance_type', sa.String(), nullable=True))
    op.add_column('maintenance_logs', sa.Column('cost', sa.Float(), nullable=True))
    op.add_column('maintenance_logs', sa.Column('service_center', sa.String(), nullable=True))
    op.add_column('maintenance_logs', sa.Column('scheduled_date', sa.Date(), nullable=True))
    op.add_column('maintenance_logs', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('maintenance_logs', sa.Column('final_cost', sa.Float(), nullable=True))
    op.add_column('maintenance_logs', sa.Column('completion_notes', sa.String(), nullable=True))
    op.alter_column('maintenance_logs', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('maintenance_logs', 'opened_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('trips', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trips', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('maintenance_logs', 'opened_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('maintenance_logs', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('maintenance_logs', 'completion_notes')
    op.drop_column('maintenance_logs', 'final_cost')
    op.drop_column('maintenance_logs', 'notes')
    op.drop_column('maintenance_logs', 'scheduled_date')
    op.drop_column('maintenance_logs', 'service_center')
    op.drop_column('maintenance_logs', 'cost')
    op.drop_column('maintenance_logs', 'maintenance_type')
    # ### end Alembic commands ###
